version: '3.9'

services:
  frontend:
    build:
      context: easy-cash-frontend
      target: builder
    ports:
      - 4200:4200
  backend:
    build: easy-cash-backend
    ports:
      - 8081:80
    depends_on:
      db:
        condition: service_healthy
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password1$$
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    restart: unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password1$$ -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
   