version: '3.4'

services:
  backend:
    image: easy-cash-api
    ports:
            - "7000:80"
            - "7024:443"
    build:
      context: ./easy-cash-backend/
      dockerfile: Dockerfile
    depends_on:
            - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          MSSQL_SA_PASSWORD: "password123"
          ACCEPT_EULA: "Y"
  frontend:
        image: easy-cash-frontend
        build: 
            context: ./easy-cash-frontend/
            dockerfile: Dockerfile
        ports: 
          - "5006:80"
          - "5007:443"
        depends_on: 
          - backend